[versions]
agp = "9.2.1"
libxposedApi = "102.0.0"
dexkit = "2.2.0"

[libraries]
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "libxposedApi" }
dexkit = { group = "org.luckypray", name = "dexkit", version.ref = "dexkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }